version: "2"
services: 
  api:
    container_name: api
    restart: always
    build: .
    volumes:
     - .:/usr/src/app
    ports:
     - "3000:3000"
    environment:
     - FilePath=/usr/src/app/Volumes
     - MONGO_HOST=mongo
     - MONGO_URI=mongodb://mongo:27018/filedb
    links:
     - mongo
  mongo: 
    container_name: mongo
    image: mongo
    command: mongod --port 27018
    volumes:
     - ./data:/data/db
    ports:
     - "27018:27018"